#!/usr/bin/env bash
# Simple launcher for Tidy, mainly for snap maintainence purpose
# 林博仁(Buo-ren, Lin) © 2018

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

{
	printf \
		-- \
		'tiny-launch: Warning: This snap is now obselute due to the snap name migration, and will no longer recieve update.\n'
	printf \
		-- \
		'tiny-launch: Info: Remove the `tiny-brlin` snap and install the new `tiny` snap to manually fix it.\n'
} 1>&2

exec tidy "${@}"